/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelValorDosis.java
 *
 * Created on 12/06/2009, 00:01:59
 */
package ar.com.init.agros.view.components.valores;

import ar.com.init.agros.model.ValorDosis;
import ar.com.init.agros.util.gui.validation.components.FrameNotifier;
import ar.com.init.agros.util.gui.validation.inputverifiers.DecimalInputVerifier;
import javax.swing.InputVerifier;

/**
 *
 * @author gmatheu
 */
public class PanelValorDosis extends javax.swing.JPanel
{

    private static final long serialVersionUID = -1L;
    private ValorDosis valorDosis;
    private FrameNotifier frameNotifier;

    /** Creates new form PanelValorDosis */
    public PanelValorDosis()
    {
        initComponents();
    }

    public ValorDosis getValorDosis()
    {
        if (valorDosis == null) {
            valorDosis = new ValorDosis();
        }

        valorDosis.setFormattedValue(jTextFieldDosis.getText());

        if (!valorDosis.isValid()) {
            return null;
        }

        return valorDosis;
    }

    public void setValorDosis(ValorDosis valorDosis)
    {
        if (valorDosis == null) {
            jTextFieldDosis.setText("");
        }
        else {
            jTextFieldDosis.setText(valorDosis.getFormattedValue());
        }
        this.valorDosis = valorDosis;
    }

    public FrameNotifier getFrameNotifier()
    {
        return frameNotifier;
    }

    public void clear()
    {
        valorDosis = null;
        jTextFieldDosis.setText("");
    }

    public void setFrameNotifier(FrameNotifier frameNotifier)
    {
        this.frameNotifier = frameNotifier;
        jTextFieldDosis.setInputVerifier(new DecimalInputVerifier(frameNotifier,false));
    }

    @Override
    public InputVerifier getInputVerifier()
    {
        return this.jTextFieldDosis.getInputVerifier();
    }

    @Override
    public void setInputVerifier(InputVerifier inputVerifier)
    {
        this.jTextFieldDosis.setInputVerifier(inputVerifier);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDosis = new javax.swing.JTextField();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(PanelValorDosis.class);
        jTextFieldDosis.setText(resourceMap.getString("jTextFieldDosis.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldDosis, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldDosis)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextFieldDosis;
    // End of variables declaration//GEN-END:variables
}
