/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogInformacionAgroquimico.java
 *
 * Created on 27/07/2009, 21:45:10
 */
package ar.com.init.agros.view.agroquimicos;

import ar.com.init.agros.conf.GuiaFitosanitariaMgr;
import ar.com.init.agros.model.InformacionAgroquimico;
import ar.com.init.agros.util.gui.AbstractEventControl;
import ar.com.init.agros.util.gui.validation.components.FrameNotifier;
import java.awt.Desktop;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;
import org.xito.dialog.DialogManager;

/**
 *
 * @author gmatheu
 */
public class DialogInformacionAgroquimico extends javax.swing.JDialog
{

    private static final long serialVersionUID = -1L;
    private InformacionAgroquimico informacionAgroquimico;

    /** Creates new form DialogInformacionAgroquimico */
    public DialogInformacionAgroquimico(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    DialogInformacionAgroquimico(Frame currentFrame, InformacionAgroquimico ia)
    {
        super(currentFrame);
        setLocationRelativeTo(currentFrame);
        initComponents();
        setInformacionAgroquimico(ia);
        oKCancelCleanPanel.disableForList();
        oKCancelCleanPanel.setListenerToButtons(new OkCleanCancelEventControl());
        oKCancelCleanPanel.setOwner(this);
    }

    public InformacionAgroquimico getInformacionAgroquimico()
    {
        return informacionAgroquimico;
    }

    public void setInformacionAgroquimico(InformacionAgroquimico informacionAgroquimico)
    {
        this.informacionAgroquimico = informacionAgroquimico;
        textFieldNombreComercial.setText(informacionAgroquimico.getNombreComercial());
        textFieldPpioActivo.setText(informacionAgroquimico.getPrincipioActivo());
        textFieldConcentracion.setText(informacionAgroquimico.getConcentracion());

        jButtonDetalle.setEnabled(
                informacionAgroquimico.getRutaPdf() != null && informacionAgroquimico.getRutaPdf().length() > 0);

        String acc = informacionAgroquimico.getStringAcciones();
        textFieldUso.setText(acc);
    }

    private class OkCleanCancelEventControl extends AbstractEventControl
    {

        @Override
        public FrameNotifier getFrameNotifier()
        {
            return null;
        }

        @Override
        public void actionPerformed(ActionEvent e)
        {
            if (e.getSource() == oKCancelCleanPanel.getBtnCancelar()) {
                DialogInformacionAgroquimico.this.dispose();
            }
        }
    };

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInformacionAgroquimico = new javax.swing.JPanel();
        jButtonDetalle = new javax.swing.JButton();
        jLabelNombreComercial = new javax.swing.JLabel();
        jLabelPpioActivo = new javax.swing.JLabel();
        jLabelConcentracion = new javax.swing.JLabel();
        jLabelUso = new javax.swing.JLabel();
        textFieldNombreComercial = new javax.swing.JLabel();
        textFieldPpioActivo = new javax.swing.JLabel();
        textFieldConcentracion = new javax.swing.JLabel();
        textFieldUso = new javax.swing.JLabel();
        oKCancelCleanPanel = new ar.com.init.agros.util.gui.components.buttons.OKCancelCleanPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(DialogInformacionAgroquimico.class);
        jPanelInformacionAgroquimico.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanelInformacionAgroquimico.border.title"))); // NOI18N
        jPanelInformacionAgroquimico.setName("jPanelInformacionAgroquimico"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getActionMap(DialogInformacionAgroquimico.class, this);
        jButtonDetalle.setAction(actionMap.get("verDetalle")); // NOI18N
        jButtonDetalle.setText(resourceMap.getString("jButtonDetalle.text")); // NOI18N
        jButtonDetalle.setName("jButtonDetalle"); // NOI18N

        jLabelNombreComercial.setText(resourceMap.getString("jLabelNombreComercial.text")); // NOI18N
        jLabelNombreComercial.setName("jLabelNombreComercial"); // NOI18N

        jLabelPpioActivo.setText(resourceMap.getString("jLabelPpioActivo.text")); // NOI18N
        jLabelPpioActivo.setName("jLabelPpioActivo"); // NOI18N

        jLabelConcentracion.setText(resourceMap.getString("jLabelConcentracion.text")); // NOI18N
        jLabelConcentracion.setName("jLabelConcentracion"); // NOI18N

        jLabelUso.setText(resourceMap.getString("jLabelUso.text")); // NOI18N
        jLabelUso.setName("jLabelUso"); // NOI18N

        textFieldNombreComercial.setFont(resourceMap.getFont("labelField.font")); // NOI18N
        textFieldNombreComercial.setText(resourceMap.getString("textFieldNombreComercial.text")); // NOI18N
        textFieldNombreComercial.setName("textFieldNombreComercial"); // NOI18N

        textFieldPpioActivo.setFont(resourceMap.getFont("labelField.font")); // NOI18N
        textFieldPpioActivo.setText(resourceMap.getString("textFieldPpioActivo.text")); // NOI18N
        textFieldPpioActivo.setName("textFieldPpioActivo"); // NOI18N

        textFieldConcentracion.setFont(resourceMap.getFont("labelField.font")); // NOI18N
        textFieldConcentracion.setText(resourceMap.getString("textFieldConcentracion.text")); // NOI18N
        textFieldConcentracion.setName("textFieldConcentracion"); // NOI18N

        textFieldUso.setFont(resourceMap.getFont("labelField.font")); // NOI18N
        textFieldUso.setText(resourceMap.getString("textFieldUso.text")); // NOI18N
        textFieldUso.setName("textFieldUso"); // NOI18N

        javax.swing.GroupLayout jPanelInformacionAgroquimicoLayout = new javax.swing.GroupLayout(jPanelInformacionAgroquimico);
        jPanelInformacionAgroquimico.setLayout(jPanelInformacionAgroquimicoLayout);
        jPanelInformacionAgroquimicoLayout.setHorizontalGroup(
            jPanelInformacionAgroquimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformacionAgroquimicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformacionAgroquimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInformacionAgroquimicoLayout.createSequentialGroup()
                        .addGroup(jPanelInformacionAgroquimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelConcentracion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPpioActivo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNombreComercial, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInformacionAgroquimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldPpioActivo, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(textFieldNombreComercial, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(textFieldConcentracion, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(textFieldUso, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelInformacionAgroquimicoLayout.setVerticalGroup(
            jPanelInformacionAgroquimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacionAgroquimicoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelInformacionAgroquimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textFieldNombreComercial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNombreComercial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacionAgroquimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPpioActivo)
                    .addComponent(textFieldPpioActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanelInformacionAgroquimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFieldConcentracion, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                    .addComponent(jLabelConcentracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacionAgroquimicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFieldUso, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                    .addComponent(jLabelUso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        oKCancelCleanPanel.setName("oKCancelCleanPanel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInformacionAgroquimico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oKCancelCleanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelInformacionAgroquimico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(oKCancelCleanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void verDetalle()
    {
        File pdf = new File(GuiaFitosanitariaMgr.translateToPdfPath(
                informacionAgroquimico.getRutaPdf()));

        if (pdf.exists()) {
            try {
                Desktop.getDesktop().open(pdf);
            }
            catch (IOException ex) {
                DialogManager.showError(null, "Ver Detalle",
                        "Hubo un error abriendo el archivo pdf: " + pdf.getAbsolutePath(), null);
                Logger.getLogger(DialogInformacionAgroquimico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            DialogManager.showError(null, "Ver Detalle",
                    "No se pudo encontrar el archivo pdf: " + pdf.getAbsolutePath(), null);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalle;
    private javax.swing.JLabel jLabelConcentracion;
    private javax.swing.JLabel jLabelNombreComercial;
    private javax.swing.JLabel jLabelPpioActivo;
    private javax.swing.JLabel jLabelUso;
    private javax.swing.JPanel jPanelInformacionAgroquimico;
    private ar.com.init.agros.util.gui.components.buttons.OKCancelCleanPanel oKCancelCleanPanel;
    private javax.swing.JLabel textFieldConcentracion;
    private javax.swing.JLabel textFieldNombreComercial;
    private javax.swing.JLabel textFieldPpioActivo;
    private javax.swing.JLabel textFieldUso;
    // End of variables declaration//GEN-END:variables
}
