/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddRemoveUpdatePanel.java
 *
 * Created on 15-jul-2009, 17:14:04
 */
package ar.com.init.agros.util.gui.components.buttons;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author fbobbio
 */
public class AddRemoveUpdatePanel extends javax.swing.JPanel
{
    /** Creates new form AddRemoveUpdatePanel */
    public AddRemoveUpdatePanel()
    {
        initComponents();
    }

    public JButton getJButtonUpdate()
    {
        return jButtonUpdate;
    }

    public JButton getJButtonAdd()
    {
        return addRemovePanel1.getJButtonAdd();
    }

    public JButton getJButtonRemove()
    {
        return addRemovePanel1.getJButtonRemove();
    }

    public JButton getJButtonClean()
    {
        return addRemovePanel1.getJButtonClean();
    }

    @Override
    public void setEnabled(boolean enabled)
    {
        addRemovePanel1.setEnabled(enabled);
        setBtnUpdateEnabled(enabled);
    }

    public void setBtnAddEnabled(boolean enabled)
    {
        getJButtonAdd().setEnabled(enabled);
    }

    public void setBtnRemoveEnabled(boolean enabled)
    {
        getJButtonRemove().setEnabled(enabled);
    }

    public void setBtnCleanEnabled(boolean enabled)
    {
        getJButtonClean().setEnabled(enabled);
    }

    public void setBtnUpdateEnabled(boolean enabled)
    {
        jButtonUpdate.setEnabled(enabled);
    }

    public void setVisible(boolean add, boolean remove, boolean clean, boolean update)
    {
        addRemovePanel1.setVisible(add, remove, clean);
        jButtonUpdate.setVisible(update);
    }

    public void addActionListener(ActionListener evt)
    {
        addRemovePanel1.addActionListener(evt);
        jButtonUpdate.addActionListener(evt);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addRemovePanel1 = new ar.com.init.agros.util.gui.components.buttons.AddRemovePanel();
        jButtonUpdate = new javax.swing.JButton();

        add(addRemovePanel1);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(AddRemoveUpdatePanel.class);
        jButtonUpdate.setIcon(resourceMap.getIcon("jButtonUpdate.icon")); // NOI18N
        jButtonUpdate.setText(resourceMap.getString("jButtonUpdate.text")); // NOI18N
        jButtonUpdate.setEnabled(false);
        add(jButtonUpdate);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ar.com.init.agros.util.gui.components.buttons.AddRemovePanel addRemovePanel1;
    private javax.swing.JButton jButtonUpdate;
    // End of variables declaration//GEN-END:variables

}
