/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddRemovePanel.java
 *
 * Created on 15/06/2009, 18:34:14
 */
package ar.com.init.agros.util.gui.components.buttons;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author gmatheu
 */
public class AddRemovePanel extends javax.swing.JPanel
{
    private static final long serialVersionUID = -1L;

    /** Creates new form AddRemovePanel */
    public AddRemovePanel()
    {
        initComponents();
    }

    public JButton getJButtonAdd()
    {
        return jButtonAdd;
    }

    public JButton getJButtonRemove()
    {
        return jButtonRemove;
    }

    public JButton getJButtonClean()
    {
        return jButtonClean;
    } 

    @Override
    public void setEnabled(boolean enabled)
    {
        setBtnAddEnabled(enabled);
        setBtnCleanEnabled(enabled);
        setBtnRemoveEnabled(enabled);
    }

    public void setBtnAddEnabled(boolean enabled)
    {
        jButtonAdd.setEnabled(enabled);
    }

    public void setBtnRemoveEnabled(boolean enabled)
    {
        jButtonRemove.setEnabled(enabled);
    }

    public void setBtnCleanEnabled(boolean enabled)
    {
        jButtonClean.setEnabled(enabled);
    }

    public void setVisible(boolean add, boolean remove, boolean clean)
    {
        jButtonAdd.setVisible(add);
        jButtonRemove.setVisible(remove);
        jButtonClean.setVisible(clean);
    }

    public void addActionListener(ActionListener evt)
    {
        jButtonAdd.addActionListener(evt);
        jButtonRemove.addActionListener(evt);
        jButtonClean.addActionListener(evt);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdd = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonClean = new javax.swing.JButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(AddRemovePanel.class);
        jButtonAdd.setIcon(resourceMap.getIcon("jButtonAdd.icon")); // NOI18N
        jButtonAdd.setText(resourceMap.getString("jButtonAdd.text")); // NOI18N
        jButtonAdd.setName("jButtonAdd"); // NOI18N
        add(jButtonAdd);

        jButtonRemove.setIcon(resourceMap.getIcon("jButtonRemove.icon")); // NOI18N
        jButtonRemove.setText(resourceMap.getString("jButtonRemove.text")); // NOI18N
        jButtonRemove.setName("jButtonRemove"); // NOI18N
        add(jButtonRemove);

        jButtonClean.setIcon(resourceMap.getIcon("jButtonClean.icon")); // NOI18N
        jButtonClean.setText(resourceMap.getString("jButtonClean.text")); // NOI18N
        jButtonClean.setName("jButtonClean"); // NOI18N
        add(jButtonClean);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonRemove;
    // End of variables declaration//GEN-END:variables
}
