/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AgroquimicosReportCriteria.java
 *
 * Created on 21-ago-2009, 12:14:33
 */
package ar.com.init.agros.view.reporting;

import ar.com.init.agros.controller.AgroquimicoJpaController;
import ar.com.init.agros.model.Agroquimico;
import ar.com.init.agros.model.Campania;
import ar.com.init.agros.model.MomentoAplicacion;
import ar.com.init.agros.reporting.components.ReportCriteria;
import ar.com.init.agros.util.gui.GUIUtility;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.PersistenceException;

/**
 *
 * @author fbobbio
 */
public class AgroquimicosReportCriteria extends javax.swing.JPanel implements ReportCriteria
{

    private static final long serialVersionUID = -1L;
    private CampaniasReportCriteria campaniaReportCriteria;
    private boolean useTrabajos;
    private boolean usePlanificaciones;   

    /** Creates new form AgroquimicosReportCriteria */
    public AgroquimicosReportCriteria()
    {
        initComponents();
        try {
            AgroquimicoJpaController agroquimicoJpaController = new AgroquimicoJpaController();
            dualListAgroquimicos.addAvailable(agroquimicoJpaController.findEntities());
        }
        catch (PersistenceException e) {
            GUIUtility.logPersistenceError(AgroquimicosReportCriteria.class, e);
        }
    }

    public AgroquimicosReportCriteria(CampaniasReportCriteria campaniaReportCriteria, boolean useTrabajos, boolean usePlanificaciones)
    {
        this();
        this.campaniaReportCriteria = campaniaReportCriteria;
        this.usePlanificaciones = usePlanificaciones;
        this.useTrabajos = useTrabajos;
    }

    public void setFiltroMomentoDeAplicacionVisible(boolean val)
    {
        momentoAplicacionReportCriteria1.setVisible(val);
    }

    @Override
    public String getTabTitle()
    {
        return "Agroquímicos";
    }

    @Override
    public String getErrorMessage()
    {
        return "Debe seleccionar por lo menos un Agroquímico";
    }

    @Override
    public void clear()
    {
        dualListAgroquimicos.removeAllSelected();
    }

    @Override
    public boolean validateSelection()
    {
        return dualListAgroquimicos.getSelected().size() > 0;
    }

    public List<Agroquimico> getSelectedAgroquimicos()
    {
        return dualListAgroquimicos.getSelected();
    }

    public MomentoAplicacion getSelectedMomento()
    {
        return momentoAplicacionReportCriteria1.getSelectedMomentoAplicacion();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dualListAgroquimicos = new ar.com.init.agros.util.gui.components.list.DualList();
        momentoAplicacionReportCriteria1 = new ar.com.init.agros.view.reporting.MomentoAplicacionReportCriteria();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(momentoAplicacionReportCriteria1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(dualListAgroquimicos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dualListAgroquimicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(momentoAplicacionReportCriteria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentShown
    {//GEN-HEADEREND:event_formComponentShown
        if (campaniaReportCriteria != null && campaniaReportCriteria.validateSelection()) {
            List<Campania> campanias = campaniaReportCriteria.getSelected();

            dualListAgroquimicos.clearAvailable();
            AgroquimicoJpaController agroquimicoController = new AgroquimicoJpaController();

            dualListAgroquimicos.addAvailable(agroquimicoController.findByCampanias(campanias, useTrabajos,
                    usePlanificaciones));
        }
    }//GEN-LAST:event_formComponentShown
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ar.com.init.agros.util.gui.components.list.DualList dualListAgroquimicos;
    private ar.com.init.agros.view.reporting.MomentoAplicacionReportCriteria momentoAplicacionReportCriteria1;
    // End of variables declaration//GEN-END:variables
}
