/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormaFumigacionReportCriteria.java
 *
 * Created on 20-ago-2009, 11:19:12
 */
package ar.com.init.agros.view.reporting;

import ar.com.init.agros.controller.base.NamedEntityJpaController;
import ar.com.init.agros.model.FormaFumigacion;
import ar.com.init.agros.reporting.components.ReportCriteria;
import ar.com.init.agros.util.gui.GUIUtility;
import javax.persistence.PersistenceException;

/**
 *
 * @author fbobbio
 */
public class FormaFumigacionReportCriteria extends javax.swing.JPanel implements ReportCriteria
{
    private NamedEntityJpaController<FormaFumigacion> formaFumigacionJpaController;

    /** Creates new form FormaFumigacionReportCriteria */
    public FormaFumigacionReportCriteria()
    {
        formaFumigacionJpaController = new NamedEntityJpaController<FormaFumigacion>(FormaFumigacion.class);
        initComponents();
        try
        {
            GUIUtility.refreshComboBox(formaFumigacionJpaController.findEntities(), jComboBoxFormaFumigacion);
        }
        catch (PersistenceException e)
        {
            GUIUtility.logPersistenceError(FormaFumigacionReportCriteria.class, e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxFormaFumigacion = new javax.swing.JComboBox();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(FormaFumigacionReportCriteria.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFormaFumigacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxFormaFumigacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxFormaFumigacion;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean validateSelection()
    {
        return true;
    }

    @Override
    public void clear()
    {
        jComboBoxFormaFumigacion.setSelectedIndex(0);
    }

    @Override
    public String getTabTitle()
    {
        return "Forma de Fumigación";
    }

    @Override
    public String getErrorMessage()
    {
        return "";
    }
}
