/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MomentoAplicacionReportCriteria.java
 *
 * Created on 20-ago-2009, 12:04:00
 */
package ar.com.init.agros.view.reporting;

import ar.com.init.agros.controller.base.NamedEntityJpaController;
import ar.com.init.agros.model.MomentoAplicacion;
import ar.com.init.agros.reporting.components.ReportCriteria;
import ar.com.init.agros.util.gui.GUIUtility;
import javax.persistence.PersistenceException;

/**
 *
 * @author fbobbio
 */
public class MomentoAplicacionReportCriteria extends javax.swing.JPanel implements ReportCriteria
{
    private NamedEntityJpaController<MomentoAplicacion> momentoAplicacionJpaController;

    /** Creates new form MomentoAplicacionReportCriteria */
    public MomentoAplicacionReportCriteria()
    {
        momentoAplicacionJpaController = new NamedEntityJpaController<MomentoAplicacion>(MomentoAplicacion.class);
        initComponents();
        try
        {
            GUIUtility.refreshComboBox(momentoAplicacionJpaController.findEntities(), jComboBoxMomentoDeAplicacion);
        }
        catch (PersistenceException e)
        {
            GUIUtility.logPersistenceError(MomentoAplicacionReportCriteria.class, e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxMomentoDeAplicacion = new javax.swing.JComboBox();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(MomentoAplicacionReportCriteria.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxMomentoDeAplicacion, 0, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxMomentoDeAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxMomentoDeAplicacion;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean validateSelection()
    {
        return true;
    }

    @Override
    public void clear()
    {
        jComboBoxMomentoDeAplicacion.setSelectedIndex(0);
    }

    @Override
    public String getTabTitle()
    {
        return "Momento de Aplicación";
    }

    @Override
    public String getErrorMessage()
    {
        return "";
    }

    public MomentoAplicacion getSelectedMomentoAplicacion()
    {
        if (jComboBoxMomentoDeAplicacion.getSelectedItem() instanceof MomentoAplicacion)
        {
            return (MomentoAplicacion)jComboBoxMomentoDeAplicacion.getSelectedItem();
        }
        else
        {
            return null;
        }
    }
}
