/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PeriodosReportCriteria.java
 *
 * Created on 26-ago-2009, 11:06:59
 */
package ar.com.init.agros.view.reporting;

import ar.com.init.agros.reporting.components.ReportCriteria;
import ar.com.init.agros.util.gui.Periodo;
import ar.com.init.agros.util.gui.exceptions.InvalidDateRangeException;
import ar.com.init.agros.util.gui.validation.components.FrameNotifier;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author fbobbio
 */
public class PeriodosReportCriteria extends javax.swing.JPanel implements ReportCriteria
{

    private DefaultListModel listModel;
    private FrameNotifier frameNotifier;

    /** Creates new form PeriodosReportCriteria */
    public PeriodosReportCriteria()
    {
        listModel = new DefaultListModel();
        initComponents();
        jListPeriodos.setModel(listModel);
        jListPeriodos.setCellRenderer(listableListRenderer1);
        addRemovePanel1.addActionListener(new EventoAddRemoveClean());
    }

    public void setFrameNotifier(FrameNotifier frameNotifier)
    {
        this.frameNotifier = frameNotifier;
    }

    class EventoAddRemoveClean implements ActionListener
    {

        @Override
        public void actionPerformed(ActionEvent e)
        {
            if (e.getSource() == addRemovePanel1.getJButtonAdd())
            {
                try
                {
                    Periodo p = new Periodo(rangeDateChooser1.getFromDate(), rangeDateChooser1.getToDate());
                    listModel.addElement(p);
                }
                catch (InvalidDateRangeException ex)
                {
                    frameNotifier.showErrorMessage(ex.getLocalizedMessage());
                }
            }
            if (e.getSource() == addRemovePanel1.getJButtonClean())
            {
                clear();
            }
            if (e.getSource() == addRemovePanel1.getJButtonRemove())
            {
                remove();
            }
        }
    }

    private void remove()
    {
        for (Object l : jListPeriodos.getSelectedValues())
        {
            listModel.removeElement(l);
        }
    }

    @Override
    public boolean validateSelection()
    {
        return listModel.size() > 0;
    }

    @Override
    public void clear()
    {
        listModel.clear();
    }

    @Override
    public String getTabTitle()
    {
        return "Períodos";
    }

    @Override
    public String getErrorMessage()
    {
        return "Debe seleccionar al menos un Período";
    }

    public List<Periodo> getPeriodos()
    {
        return (List<Periodo>) Collections.list(listModel.elements());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listableListRenderer1 = new ar.com.init.agros.util.gui.ListableListRenderer();
        rangeDateChooser1 = new ar.com.init.agros.util.gui.components.date.RangeDateChooser();
        addRemovePanel1 = new ar.com.init.agros.util.gui.components.buttons.AddRemovePanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPeriodos = new javax.swing.JList();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(PeriodosReportCriteria.class);
        listableListRenderer1.setText(resourceMap.getString("listableListRenderer1.text")); // NOI18N

        jScrollPane1.setViewportView(jListPeriodos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(addRemovePanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(rangeDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rangeDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addRemovePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ar.com.init.agros.util.gui.components.buttons.AddRemovePanel addRemovePanel1;
    private javax.swing.JList jListPeriodos;
    private javax.swing.JScrollPane jScrollPane1;
    private ar.com.init.agros.util.gui.ListableListRenderer listableListRenderer1;
    private ar.com.init.agros.util.gui.components.date.RangeDateChooser rangeDateChooser1;
    // End of variables declaration//GEN-END:variables
}
