/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelCostosComercializacion.java
 *
 * Created on 07-feb-2010, 17:02:58
 */
package ar.com.init.agros.view.costos;

import ar.com.init.agros.controller.SiembraJpaController;
import ar.com.init.agros.model.Campania;
import ar.com.init.agros.model.Siembra;
import ar.com.init.agros.util.gui.GUIUtility;
import ar.com.init.agros.util.gui.table.TablizableEntityDataModel;
import ar.com.init.agros.util.gui.validation.components.FrameNotifier;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;

/**
 *
 * @author fbobbio
 */
public class PanelCostosComercializacion extends JPanel {

    private FrameNotifier frameNotifier;
    private TablizableEntityDataModel<Siembra> tableModel;
    private Campania campania;
    private SiembraJpaController siembraController;
    private DialogCostosPostCosecha dialog;

    /** Creates new form PanelCostosComercializacion */
    public PanelCostosComercializacion() {
        tableModel = new TablizableEntityDataModel<Siembra>(Siembra.TABLE_HEADERS);
        initComponents();
        siembraController = new SiembraJpaController();

        ListSelectionModel rowsModel = jXTable1.getSelectionModel();
        rowsModel.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (jXTable1.getSelectedRow() != -1) {
                    jButtonCargarCostos.setEnabled(true);
                } else {
                    jButtonCargarCostos.setEnabled(false);
                }
            }
        });
    }

    public void disableFields() {
        jXTable1.setEnabled(false);
    }

    public FrameNotifier getFrameNotifier() {
        return frameNotifier;
    }

    public void setFrameNotifier(FrameNotifier frameNotifier) {
        this.frameNotifier = frameNotifier;
    }

    public List<Siembra> getSiembras() {
        return tableModel.getData();
    }

    public void refreshSiembras() {
        if (campania != null) {
            List<Siembra> siembras = siembraController.findSiembrasPorCampania(campania);
            tableModel.setData(siembras);
            jXTable1.setModel(tableModel);
        } else {
            tableModel.setData(null);
        }
    }

    public Campania getCampania() {
        return campania;
    }

    public void setCampania(Campania campania) {
        this.campania = campania;
        refreshSiembras();
    }

    public void clear() {
        for (Siembra s : tableModel.getData()) {
            s.getCostosPostCosecha().clear();
        }
    }

    public TableModel getModel() {
        return tableModel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jButtonCargarCostos = new javax.swing.JButton();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jXTable1.setName("jXTable1"); // NOI18N
        jXTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jXTable1);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(PanelCostosComercializacion.class);
        jButtonCargarCostos.setText(resourceMap.getString("jButtonCargarCostos.text")); // NOI18N
        jButtonCargarCostos.setEnabled(false);
        jButtonCargarCostos.setName("jButtonCargarCostos"); // NOI18N
        jButtonCargarCostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarCostosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCargarCostos)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCargarCostos)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargarCostosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCargarCostosActionPerformed
    {//GEN-HEADEREND:event_jButtonCargarCostosActionPerformed
        Siembra s = tableModel.getData().get(GUIUtility.getModelRowIndex(jXTable1, jXTable1.getSelectedRow()));
        dialog = new DialogCostosPostCosecha(GUIUtility.getParentFrame(this), true, s);
        dialog.setVisible(true);
        jXTable1.repaint();
    }//GEN-LAST:event_jButtonCargarCostosActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargarCostos;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables
}
