/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RangeDateChooser.java
 *
 * Created on 13/06/2009, 17:22:59
 */
package ar.com.init.agros.util.gui.components.date;

import ar.com.init.agros.util.gui.validation.components.FrameNotifier;
import java.util.Date;

/**
 *
 * @author gmatheu
 */
public class RangeDateChooser extends javax.swing.JPanel
{

    private static final long serialVersionUID = -1L;
    private FrameNotifier frameNotifier;

    /** Creates new form RangeDateChooser */
    public RangeDateChooser()
    {
        initComponents();
    }

    public FrameNotifier getFrameNotifier()
    {
        return frameNotifier;
    }

    public void setFrameNotifier(FrameNotifier frameNotifier)
    {
        this.frameNotifier = frameNotifier;
    }

    public Date getFromDate()
    {
        return agrosSingleDateChooserFrom.getDate();
    }

    public Date getToDate()
    {
        return agrosSingleDateChooserTo.getDate();
    }

    public void setFromDate(Date date)
    {
        agrosSingleDateChooserFrom.setDate(date);
    }

    public void setToDate(Date date)
    {
        agrosSingleDateChooserTo.setDate(date);
    }

    private void checkTo()
    {
        Date from = agrosSingleDateChooserFrom.getDate();
        Date to = agrosSingleDateChooserTo.getDate();

        if (to.before(from)) {
            agrosSingleDateChooserTo.setDate(from);
        }
    }

    private void checkFrom()
    {
        Date from = agrosSingleDateChooserFrom.getDate();
        Date to = agrosSingleDateChooserTo.getDate();

        if (from.after(to)) {
            agrosSingleDateChooserFrom.setDate(to);
        }
    }

    public void setLabelFrom(String label)
    {
        jLabelFrom.setText(label);
    }

    public void setLabelTo(String label)
    {
        jLabelTo.setText(label);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agrosSingleDateChooserFrom = new ar.com.init.agros.util.gui.components.date.SingleDateChooser();
        agrosSingleDateChooserTo = new ar.com.init.agros.util.gui.components.date.SingleDateChooser();
        jLabelTo = new javax.swing.JLabel();
        jLabelFrom = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        agrosSingleDateChooserFrom.setName("agrosSingleDateChooserFrom"); // NOI18N
        agrosSingleDateChooserFrom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                agrosSingleDateChooserFromPropertyChange(evt);
            }
        });

        agrosSingleDateChooserTo.setName("agrosSingleDateChooserTo"); // NOI18N
        agrosSingleDateChooserTo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                agrosSingleDateChooserToPropertyChange(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(RangeDateChooser.class);
        jLabelTo.setText(resourceMap.getString("jLabelTo.text")); // NOI18N
        jLabelTo.setName("jLabelTo"); // NOI18N

        jLabelFrom.setText(resourceMap.getString("jLabelFrom.text")); // NOI18N
        jLabelFrom.setName("jLabelFrom"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFrom)
                .addGap(18, 18, 18)
                .addComponent(agrosSingleDateChooserFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTo)
                .addGap(14, 14, 14)
                .addComponent(agrosSingleDateChooserTo, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabelTo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(agrosSingleDateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabelFrom)))
                    .addComponent(agrosSingleDateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agrosSingleDateChooserToPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_agrosSingleDateChooserToPropertyChange
    {//GEN-HEADEREND:event_agrosSingleDateChooserToPropertyChange
        checkFrom();
    }//GEN-LAST:event_agrosSingleDateChooserToPropertyChange

    private void agrosSingleDateChooserFromPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_agrosSingleDateChooserFromPropertyChange
    {//GEN-HEADEREND:event_agrosSingleDateChooserFromPropertyChange
        checkTo();
    }//GEN-LAST:event_agrosSingleDateChooserFromPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ar.com.init.agros.util.gui.components.date.SingleDateChooser agrosSingleDateChooserFrom;
    private ar.com.init.agros.util.gui.components.date.SingleDateChooser agrosSingleDateChooserTo;
    private javax.swing.JLabel jLabelFrom;
    private javax.swing.JLabel jLabelTo;
    // End of variables declaration//GEN-END:variables
}
