package ar.com.init.agros.view.almacenamientos;


import ar.com.init.agros.controller.almacenamiento.DepositoJpaController;
import ar.com.init.agros.controller.almacenamiento.SiloJpaController;
import ar.com.init.agros.controller.base.NamedEntityJpaController;
import ar.com.init.agros.model.almacenamiento.Almacenamiento;
import ar.com.init.agros.model.almacenamiento.Deposito;
import ar.com.init.agros.model.almacenamiento.Silo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import ar.com.init.agros.util.gui.AbstractEventControl;
import ar.com.init.agros.util.gui.GUIUtility;
import ar.com.init.agros.util.gui.validation.components.FrameNotifier;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.hibernate.exception.ConstraintViolationException;
import org.hibernate.validator.InvalidStateException;

 /*
  * Clase GUI DialogAlmacenamiento
  *
  * @author fbobbio
  * @version 01-dic-2010
  */
public class DialogAlmacenamiento extends javax.swing.JDialog
{
    private static final long serialVersionUID = -1L;
    private NamedEntityJpaController almacenamientoJpaController;
    private Almacenamiento almacenamiento;

    /** Creates new form DialogAlmacenamiento */
    public DialogAlmacenamiento(java.awt.Frame parent)
    {
        super(parent, true);
        GUIUtility.initWindow(this);
        initComponents();

        EventControl evt = new EventControl();
        oKCancelCleanPanel1.setListenerToButtons(evt);
        oKCancelCleanPanel1.setOwner(this);
    }

    public DialogAlmacenamiento(java.awt.Frame parent,Almacenamiento entity, boolean enabled)
    {
        this(parent);
        setAlmacenamiento(entity);
        setEnabled(enabled);
    }

    public Almacenamiento getAlmacenamiento()
    {
        if (almacenamiento == null)
        {
            return null;
        }
        else
        {
            almacenamiento.setDescripcion(jTextAreaDescripcion2.getText().trim());
            almacenamiento.setNombre(jTextFieldNombre.getText().trim());
            return almacenamiento;
        }
    }

    public void setAlmacenamiento(Almacenamiento almacenamiento)
    {
        if (almacenamiento instanceof Deposito)
        {
            jRadioButtonDeposito.setSelected(true);
            jRadioButtonSilo.setSelected(false);
            setDepositoSelected();
        }
        if (almacenamiento instanceof Silo)
        {
            jRadioButtonDeposito.setSelected(false);
            jRadioButtonSilo.setSelected(true);
            setSiloSelected();
        }
        jTextAreaDescripcion2.setText(almacenamiento.getDescripcion());
        jTextFieldNombre.setText(almacenamiento.getNombre());
        this.almacenamiento = almacenamiento;
    }

    @Override
    public void setEnabled(boolean b)
    {
        jTextAreaDescripcion2.setEditable(b);
        jTextFieldNombre.setEditable(b);
        jRadioButtonDeposito.setEnabled(b);
        jRadioButtonSilo.setEnabled(b);
        if (!b)
        {
            oKCancelCleanPanel1.disableForList();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        oKCancelCleanPanel1 = new ar.com.init.agros.util.gui.components.buttons.OKCancelCleanPanel();
        frameNotifier1 = new ar.com.init.agros.util.gui.validation.components.FrameNotifier();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDescripcion2 = new javax.swing.JTextArea();
        jRadioButtonDeposito = new javax.swing.JRadioButton();
        jRadioButtonSilo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        oKCancelCleanPanel1.setName("oKCancelCleanPanel1"); // NOI18N

        frameNotifier1.setName("frameNotifier1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(DialogAlmacenamiento.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextFieldNombre.setName("jTextFieldNombre"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel3.border.title"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTextAreaDescripcion2.setColumns(20);
        jTextAreaDescripcion2.setRows(5);
        jTextAreaDescripcion2.setName("jTextAreaDescripcion2"); // NOI18N
        jScrollPane3.setViewportView(jTextAreaDescripcion2);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        buttonGroup1.add(jRadioButtonDeposito);
        jRadioButtonDeposito.setText(resourceMap.getString("jRadioButtonDeposito.text")); // NOI18N
        jRadioButtonDeposito.setName("jRadioButtonDeposito"); // NOI18N
        jRadioButtonDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDepositoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonSilo);
        jRadioButtonSilo.setText(resourceMap.getString("jRadioButtonSilo.text")); // NOI18N
        jRadioButtonSilo.setName("jRadioButtonSilo"); // NOI18N
        jRadioButtonSilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSiloActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(oKCancelCleanPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
            .add(frameNotifier1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jRadioButtonDeposito)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jRadioButtonSilo))
                            .add(jTextFieldNombre, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(frameNotifier1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextFieldNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButtonDeposito)
                    .add(jRadioButtonSilo))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(oKCancelCleanPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonDepositoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonDepositoActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonDepositoActionPerformed
        setDepositoSelected();
    }//GEN-LAST:event_jRadioButtonDepositoActionPerformed

    private void setDepositoSelected()
    {
        almacenamiento = new Deposito();
        almacenamientoJpaController = new DepositoJpaController();
    }
    private void jRadioButtonSiloActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonSiloActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonSiloActionPerformed
        setSiloSelected();
    }//GEN-LAST:event_jRadioButtonSiloActionPerformed

    private void setSiloSelected()
    {
        almacenamiento = new Silo();
        almacenamientoJpaController = new SiloJpaController();
    }
    /** Clase de control de eventos que maneja los eventos de la GUI DialogAlmacenamiento y las validaciones de la misma */
    public class EventControl extends AbstractEventControl implements ActionListener
    {
        /** Método que maneja los eventos de la GUI DialogAlmacenamiento
         *  @param e el evento de acción lanzado por algún componente de la GUI
         */
        @Override
        public void actionPerformed(ActionEvent e)
        {
            if (e.getSource() == oKCancelCleanPanel1.getBtnClean())
            {
                DialogAlmacenamiento.this.clean();
            }
            else if (e.getSource() == oKCancelCleanPanel1.getBtnCancelar())
            {
                DialogAlmacenamiento.this.closeWindow();
            }
            else if (e.getSource() == oKCancelCleanPanel1.getBtnAceptar())
            {
                if (almacenamiento != null)
                {
                    if (validateInput(getAlmacenamiento()))
                    {
                        try
                        {
                            almacenamientoJpaController.persistOrUpdate(almacenamiento);
                            frameNotifier1.showInformationMessage("Se registró el almacenamiento " + almacenamiento.getNombre() + " con éxito");
                            DialogAlmacenamiento.this.clean();
                        }
                        catch (ConstraintViolationException ex)
                        {
                            frameNotifier1.showErrorMessage(
                                    "Ya existe un almacenamiento con el mismo nombre");
                        }
                        catch (InvalidStateException ex)
                        {
                            Logger.getLogger(DialogAlmacenamiento.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        catch (Exception ex)
                        {
                            Logger.getLogger(DialogAlmacenamiento.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                else
                {
                    frameNotifier1.showErrorMessage("Seleccione el tipo de almacenamiento a registrar");
                }
            }
        }

        @Override
        public FrameNotifier getFrameNotifier()
        {
            return frameNotifier1;
        }
    }

    /** Método que cierra la ventana y libera los recursos */
    public void closeWindow()
    {
        this.dispose();
    }

    /** Método donde se limpian todos los campos de la ventana */
    public void clean()
    {
        almacenamiento = null;
        jTextAreaDescripcion2.setText("");
        jTextFieldNombre.setText("");
        buttonGroup1.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private ar.com.init.agros.util.gui.validation.components.FrameNotifier frameNotifier1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonDeposito;
    private javax.swing.JRadioButton jRadioButtonSilo;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaDescripcion2;
    private javax.swing.JTextField jTextFieldNombre;
    private ar.com.init.agros.util.gui.components.buttons.OKCancelCleanPanel oKCancelCleanPanel1;
    // End of variables declaration//GEN-END:variables

}
