package ar.com.init.agros.view.servicios;

import ar.com.init.agros.controller.CampaniaJpaController;
import ar.com.init.agros.controller.ServicioJpaController;
import ar.com.init.agros.model.Campania;
import ar.com.init.agros.model.servicio.Servicio;
import ar.com.init.agros.model.servicio.TipoServicio;
import ar.com.init.agros.reporting.dj.AbstractDJReport.Template;
import ar.com.init.agros.util.gui.AbstractEventControl;
import ar.com.init.agros.util.gui.GUIUtility;
import ar.com.init.agros.util.gui.components.ExportFileChooser;
import ar.com.init.agros.util.gui.table.TableExporter;
import ar.com.init.agros.util.gui.updateui.UpdatableListener;
import ar.com.init.agros.util.gui.updateui.UpdatableSubject;
import ar.com.init.agros.util.gui.validation.components.FrameNotifier;
import ar.com.init.agros.view.Application;
import ar.com.init.agros.view.servicios.model.CompradorTableModel;
import ar.com.init.agros.view.servicios.model.ContratistaPostCosechaTableModel;
import ar.com.init.agros.view.servicios.model.FiltroServiciosTableModel;
import ar.com.init.agros.view.servicios.model.ProveedorInsumosTableModel;
import ar.com.init.agros.view.servicios.model.ServicioTableModel;
import ar.com.init.agros.view.servicios.model.ServiciosTotalesTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import javax.persistence.PersistenceException;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/*
 * Clase GUI FrameReporteEmpresasDeServicios
 *
 * @author fbobbio
 * @version 18-dic-2010
 */
public class FrameReporteEmpresasDeServicios extends javax.swing.JFrame implements UpdatableListener {

    private static final Logger logger = Logger.getLogger(FrameReporteEmpresasDeServicios.class.getName());
    private EventControl evt;
    private FiltroServiciosTableModel filtroServiciosTableModel;
    private ServicioJpaController servicioController;
    private CampaniaJpaController campaniaController;
    private ServiciosTotalesTableModel serviciosTotales;
    private TipoServicio tipoSeleccionado;

    /** Crea una nueva GUI tipo FrameReporteEmpresasDeServicios */
    public FrameReporteEmpresasDeServicios() {
        GUIUtility.initWindow(this);
        initComponents();
        UpdatableSubject.addUpdatableListener(this);
        oKCancelCleanPanel1.setVisible(false, true, true);
        servicioController = new ServicioJpaController();
        campaniaController = new CampaniaJpaController();
        filtroServiciosTableModel = new FiltroServiciosTableModel();
        jXTableFiltro.setModel(filtroServiciosTableModel);

        evt = new EventControl();
        jButtonExcel.addActionListener(evt);
        jButtonPDF.addActionListener(evt);
        oKCancelCleanPanel1.setListenerToButtons(evt);

        try {
            refreshUI();
            jXTableFiltro.packAll();
            jXTableDatos.packAll();
        } catch (PersistenceException e) {
            if (frameNotifier1 != null) {
                frameNotifier1.showErrorMessage(e.getLocalizedMessage());
            }
            GUIUtility.logPersistenceError(FrameReporteEmpresasDeServicios.class, e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        listableComboBoxRenderer1 = new ar.com.init.agros.util.gui.ListableComboBoxRenderer();
        frameNotifier1 = new ar.com.init.agros.util.gui.validation.components.FrameNotifier();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelFiltros = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonProveedorInsumos = new javax.swing.JRadioButton();
        jRadioButtonComprador = new javax.swing.JRadioButton();
        jRadioButtonContratista = new javax.swing.JRadioButton();
        jRadioButtonProveedorPostCosecha = new javax.swing.JRadioButton();
        jRadioButtonOtros = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTableFiltro = new org.jdesktop.swingx.JXTable();
        jComboBoxCampania = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanelReporte = new javax.swing.JPanel();
        jPanelDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTableDatos = new org.jdesktop.swingx.JXTable();
        jPanelBotones = new javax.swing.JPanel();
        jButtonPDF = new javax.swing.JButton();
        jButtonExcel = new javax.swing.JButton();
        oKCancelCleanPanel1 = new ar.com.init.agros.util.gui.components.buttons.OKCancelCleanPanel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(FrameReporteEmpresasDeServicios.class);
        listableComboBoxRenderer1.setText(resourceMap.getString("listableComboBoxRenderer1.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N

        buttonGroup1.add(jRadioButtonProveedorInsumos);
        jRadioButtonProveedorInsumos.setText(resourceMap.getString("jRadioButtonProveedorInsumos.text")); // NOI18N
        jRadioButtonProveedorInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonProveedorInsumosActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonProveedorInsumos);

        buttonGroup1.add(jRadioButtonComprador);
        jRadioButtonComprador.setText(resourceMap.getString("jRadioButtonComprador.text")); // NOI18N
        jRadioButtonComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCompradorActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonComprador);

        buttonGroup1.add(jRadioButtonContratista);
        jRadioButtonContratista.setText(resourceMap.getString("jRadioButtonContratista.text")); // NOI18N
        jRadioButtonContratista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonContratistaActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonContratista);

        buttonGroup1.add(jRadioButtonProveedorPostCosecha);
        jRadioButtonProveedorPostCosecha.setText(resourceMap.getString("jRadioButtonProveedorPostCosecha.text")); // NOI18N
        jRadioButtonProveedorPostCosecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonProveedorPostCosechaActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonProveedorPostCosecha);

        buttonGroup1.add(jRadioButtonOtros);
        jRadioButtonOtros.setText(resourceMap.getString("jRadioButtonOtros.text")); // NOI18N
        jRadioButtonOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOtrosActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonOtros);

        jScrollPane2.setViewportView(jXTableFiltro);

        jComboBoxCampania.setRenderer(listableComboBoxRenderer1);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N

        org.jdesktop.layout.GroupLayout jPanelFiltrosLayout = new org.jdesktop.layout.GroupLayout(jPanelFiltros);
        jPanelFiltros.setLayout(jPanelFiltrosLayout);
        jPanelFiltrosLayout.setHorizontalGroup(
            jPanelFiltrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelFiltrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanelFiltrosLayout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jComboBoxCampania, 0, 275, Short.MAX_VALUE)
                        .add(295, 295, 295)))
                .addContainerGap())
        );
        jPanelFiltrosLayout.setVerticalGroup(
            jPanelFiltrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelFiltrosLayout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelFiltrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxCampania, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addContainerGap())
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanelFiltros.TabConstraints.tabTitle"), jPanelFiltros); // NOI18N

        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanelDatos.border.title"))); // NOI18N

        jScrollPane1.setViewportView(jXTableDatos);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getActionMap(FrameReporteEmpresasDeServicios.class, this);
        jButtonPDF.setAction(actionMap.get("exportToPDF")); // NOI18N
        jButtonPDF.setIcon(resourceMap.getIcon("jButtonPDF.icon")); // NOI18N
        jButtonPDF.setText(resourceMap.getString("jButtonPDF.text")); // NOI18N
        jPanelBotones.add(jButtonPDF);

        jButtonExcel.setAction(actionMap.get("exportToExcel")); // NOI18N
        jButtonExcel.setIcon(resourceMap.getIcon("jButtonExcel.icon")); // NOI18N
        jButtonExcel.setText(resourceMap.getString("jButtonExcel.text")); // NOI18N
        jPanelBotones.add(jButtonExcel);
        jPanelBotones.add(oKCancelCleanPanel1);

        org.jdesktop.layout.GroupLayout jPanelDatosLayout = new org.jdesktop.layout.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanelBotones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelDatosLayout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelBotones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanelReporteLayout = new org.jdesktop.layout.GroupLayout(jPanelReporte);
        jPanelReporte.setLayout(jPanelReporteLayout);
        jPanelReporteLayout.setHorizontalGroup(
            jPanelReporteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelReporteLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelDatos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelReporteLayout.setVerticalGroup(
            jPanelReporteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelReporteLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelDatos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanelReporte.TabConstraints.tabTitle"), jPanelReporte); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(frameNotifier1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(frameNotifier1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonProveedorInsumosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonProveedorInsumosActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonProveedorInsumosActionPerformed
        refreshTablaFiltros(TipoServicio.PROVEEDOR_INSUMOS);
        jComboBoxCampania.setSelectedIndex(0);
        jComboBoxCampania.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonProveedorInsumosActionPerformed

    private void jRadioButtonCompradorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonCompradorActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonCompradorActionPerformed
        refreshTablaFiltros(TipoServicio.COMPRADOR);
        jComboBoxCampania.setSelectedIndex(0);
        jComboBoxCampania.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonCompradorActionPerformed

    private void jRadioButtonContratistaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonContratistaActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonContratistaActionPerformed
        refreshTablaFiltros(TipoServicio.CONTRATISTA);
        jComboBoxCampania.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonContratistaActionPerformed

    private void jRadioButtonProveedorPostCosechaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonProveedorPostCosechaActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonProveedorPostCosechaActionPerformed
        refreshTablaFiltros(TipoServicio.PROVEEDOR_POST_COSECHA);
        jComboBoxCampania.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonProveedorPostCosechaActionPerformed

    private void jRadioButtonOtrosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonOtrosActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonOtrosActionPerformed
        refreshTablaFiltros(TipoServicio.OTROS);
        jComboBoxCampania.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonOtrosActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jTabbedPane1StateChanged
    {//GEN-HEADEREND:event_jTabbedPane1StateChanged
        if (jTabbedPane1.getSelectedIndex() == 1) {
            if (validateFiltros()) {
                refreshDataTable();
            } else {
                jTabbedPane1.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        clear();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void refreshTablaFiltros(TipoServicio tipo) {
        tipoSeleccionado = tipo;
        if (tipo != null) {
            filtroServiciosTableModel.setData(servicioController.findByTipo(tipo));
        } else {
            filtroServiciosTableModel.setData(new ArrayList<Servicio>());
        }
    }

    private List<Servicio> getServiciosSeleccionados() {
        return filtroServiciosTableModel.getCheckedData();
    }

    private Campania getCampaniaSeleccionada() {
        if (jComboBoxCampania.getSelectedItem() instanceof Campania) {
            return (Campania) jComboBoxCampania.getSelectedItem();
        } else {
            return null;
        }
    }

    private boolean validateFiltros() {
        if (tipoSeleccionado == null) {
            frameNotifier1.showErrorMessage("Debe seleccionar el tipo de servicio que se quiere consultar");
            return false;
        }
        if (getServiciosSeleccionados().size() <= 0) {
            frameNotifier1.showErrorMessage("Debe seleccionar al menos una Empresa de Servicio a consultar");
            return false;
        }
        if (jComboBoxCampania.isEnabled()) {
            if (getCampaniaSeleccionada() == null) {
                frameNotifier1.showErrorMessage("Debe seleccionar la campaña sobre la cual se desean conocer los servicios");
                return false;
            }
        }

        frameNotifier1.showOkMessage();
        return true;
    }

    @Override
    public void refreshUI() {
        GUIUtility.refreshComboBox(campaniaController.findEntities(), jComboBoxCampania);
    }

    @Override
    public boolean isNowVisible() {
        return this.isVisible();
    }

    @Action
    public Task exportToPDF() {
        return new Task(Application.getApplication()) {

            @Override
            protected Object doInBackground() throws Exception {
                try {
                    String file = ExportFileChooser.showPDFFileChooser(FrameReporteEmpresasDeServicios.this);
                    if (jXTableDatos.getModel() != null && jXTableDatos.getModel() instanceof ServicioTableModel) {
                        serviciosTotales = new ServiciosTotalesTableModel();
                        serviciosTotales.setData(((ServicioTableModel) jXTableDatos.getModel()).sumarizarImportesPorServicio());
                    }

                    if (file == null || file.length() > 0 && jXTableDatos.getModel() != null && serviciosTotales != null) {
                        TableExporter te = createTableExporter();
                        te.exportToPDF("Reporte de Empresas de Servicios", file);
                    }
                } catch (Exception ex) {
                    frameNotifier1.showErrorMessage("No se pudo realizar la exportación correctamente");
                    ex.printStackTrace();
                }
                return "";
            }
        };
    }

    @Action
    public Task exportToExcel() {
        return new Task(Application.getApplication()) {

            @Override
            protected Object doInBackground() throws Exception {
                try {
                    String file = ExportFileChooser.showExcelFileChooser(FrameReporteEmpresasDeServicios.this);

                    if (jXTableDatos.getModel() != null && jXTableDatos.getModel() instanceof ServicioTableModel) {
                        serviciosTotales = new ServiciosTotalesTableModel();
                        serviciosTotales.setData(((ServicioTableModel) jXTableDatos.getModel()).sumarizarImportesPorServicio());
                    }
                    if (file == null || file.length() > 0 && jXTableDatos.getModel() != null && serviciosTotales != null) {
                        TableExporter te = createTableExporter();
                        te.exportToExcel("Reporte de Empresas de Servicios", file);
                    }
                } catch (Exception ex) {
                    frameNotifier1.showErrorMessage("No se pudo realizar la exportación correctamente");

                }
                return "";
            }
        };
    }

    private TableExporter createTableExporter() {
        TableExporter r = new TableExporter();

        r.setReportTitle("Reporte de Empresas de Servicios");
        if (getCampaniaSeleccionada() != null) {
            r.setReportSubtitle(String.format("Campaña: %s", getCampaniaSeleccionada().toString()));
        }
        r.setTemplate(Template.LANDSCAPE);
        r.setMainCategoryLabel("Tipo de Empresa de Servicio:");
        r.setMainCategory(tipoSeleccionado.nombre());

        TableExporter.Table serviciosTable = new TableExporter.Table("Empresas de Servicio", jXTableDatos.getModel());
        serviciosTable.setWidths(new int[]{150, 85, 150, 150, 150, 85});
        r.addTable(serviciosTable);

        TableExporter.Table totalesTable = new TableExporter.Table("Importes Totales", serviciosTotales);
        totalesTable.setWidths(new int[]{300, 85});
        r.addTable(totalesTable);

        return r;
    }

    private void refreshDataTable() {
        if (tipoSeleccionado.equals(TipoServicio.CONTRATISTA)
                || tipoSeleccionado.equals(TipoServicio.OTROS)) {
            ContratistaPostCosechaTableModel model = new ContratistaPostCosechaTableModel();
            model.setData(servicioController.getSiembrasYPulverizacionesPorCampaniaYTipoServicio(
                    getCampaniaSeleccionada(),
                    getServiciosSeleccionados(),
                    tipoSeleccionado));
            jXTableDatos.setModel(model);
        }
        if (tipoSeleccionado.equals(TipoServicio.PROVEEDOR_POST_COSECHA)) {
            ContratistaPostCosechaTableModel model = new ContratistaPostCosechaTableModel();
            model.setData(servicioController.getSiembrasPorCampaniaYTipoServicio(
                    getCampaniaSeleccionada(),
                    getServiciosSeleccionados(),
                    tipoSeleccionado));
            jXTableDatos.setModel(model);
        }
        if (tipoSeleccionado.equals(TipoServicio.COMPRADOR)) {
            CompradorTableModel model = new CompradorTableModel();
            model.setData(servicioController.getDetallesEgresoGrano(getServiciosSeleccionados(), tipoSeleccionado));
            jXTableDatos.setModel(model);
        }
        if (tipoSeleccionado.equals(TipoServicio.PROVEEDOR_INSUMOS)) {
            ProveedorInsumosTableModel model = new ProveedorInsumosTableModel();
            model.setData(servicioController.getDetallesIngresoPorServicio(getServiciosSeleccionados(), tipoSeleccionado));
            jXTableDatos.setModel(model);
        }
    }

    /** Clase de control de eventos que maneja los eventos de la GUI FrameReporteEmpresasDeServicios y las validaciones de la misma */
    public class EventControl extends AbstractEventControl implements ActionListener {

        /** Método que maneja los eventos de la GUI FrameReporteEmpresasDeServicios
         *  @param e el evento de acción lanzado por algún componente de la GUI
         */
        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == oKCancelCleanPanel1.getBtnCancelar()) {
                clear();
                FrameReporteEmpresasDeServicios.this.dispose();
            }
            if (e.getSource() == oKCancelCleanPanel1.getBtnClean()) {
                clear();
            }
        }

        @Override
        public FrameNotifier getFrameNotifier() {
            return frameNotifier1;
        }
    }

    /** Método donde se limpian todos los campos de la ventana */
    public void clear() {
        buttonGroup1.clearSelection();
        tipoSeleccionado = null;
        jComboBoxCampania.setSelectedIndex(0);
        jTabbedPane1.setSelectedIndex(0);
        filtroServiciosTableModel.clear();
        jXTableDatos.setModel(new ContratistaPostCosechaTableModel());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private ar.com.init.agros.util.gui.validation.components.FrameNotifier frameNotifier1;
    private javax.swing.JButton jButtonExcel;
    private javax.swing.JButton jButtonPDF;
    private javax.swing.JComboBox jComboBoxCampania;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelFiltros;
    private javax.swing.JPanel jPanelReporte;
    private javax.swing.JRadioButton jRadioButtonComprador;
    private javax.swing.JRadioButton jRadioButtonContratista;
    private javax.swing.JRadioButton jRadioButtonOtros;
    private javax.swing.JRadioButton jRadioButtonProveedorInsumos;
    private javax.swing.JRadioButton jRadioButtonProveedorPostCosecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.swingx.JXTable jXTableDatos;
    private org.jdesktop.swingx.JXTable jXTableFiltro;
    private ar.com.init.agros.util.gui.ListableComboBoxRenderer listableComboBoxRenderer1;
    private ar.com.init.agros.util.gui.components.buttons.OKCancelCleanPanel oKCancelCleanPanel1;
    // End of variables declaration//GEN-END:variables
}
