/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelBonificaciones.java
 *
 * Created on 30-nov-2009, 10:24:07
 */
package ar.com.init.agros.view.components.panels;

import ar.com.init.agros.model.Bonificacion;
import ar.com.init.agros.model.Campania;
import ar.com.init.agros.util.gui.validation.components.DoubleTableCellEditor;
import ar.com.init.agros.util.gui.validation.components.FrameNotifier;
import ar.com.init.agros.util.gui.validation.inputverifiers.DecimalInputVerifier;
import ar.com.init.agros.view.campanias.model.BonificacionTableModel;
import ar.com.init.agros.view.components.editors.EditableColumnHighlighter;
import java.util.List;
import javax.swing.table.TableModel;

/**
 *
 * @author fbobbio
 */
public class PanelBonificaciones extends javax.swing.JPanel {

    private FrameNotifier frameNotifier;
    private BonificacionTableModel bonificacionesTableModel;

    /** Creates new form PanelBonificaciones */
    public PanelBonificaciones() {
        bonificacionesTableModel = new BonificacionTableModel();
        initComponents();
        jXTableBonificaciones.setModel(bonificacionesTableModel);
        setHighlighters();
        jXTableBonificaciones.packAll();
    }

    private void setHighlighters() {
        jXTableBonificaciones.setHighlighters(new EditableColumnHighlighter(BonificacionTableModel.IMPORTE_ACTIVO_COLUMN_IDX));
    }

    public List<Bonificacion> getBonificaciones() {
        return bonificacionesTableModel.getBonificaciones();
    }

    public void setCampania(Campania campania) {
        if (campania != null) {
            campania.actualizarBonificaciones();
            bonificacionesTableModel.setData(campania.getBonificaciones());
        } else {
            bonificacionesTableModel.clear();
        }
    }

    @Override
    public void setEnabled(boolean enabled) {
        jXTableBonificaciones.setEnabled(false);
    }

    public FrameNotifier getFrameNotifier() {
        return frameNotifier;
    }

    public void setFrameNotifier(FrameNotifier frameNotifier) {
        this.frameNotifier = frameNotifier;
        DoubleTableCellEditor tableCellEditor = new DoubleTableCellEditor(frameNotifier);
        tableCellEditor.changeInputVerifier(new DecimalInputVerifier(frameNotifier, false));
        jXTableBonificaciones.setDefaultEditor(Double.class, tableCellEditor);
    }

    public TableModel getModel() {
        return bonificacionesTableModel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTableBonificaciones = new org.jdesktop.swingx.JXTable();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jXTableBonificaciones.setName("jXTableBonificaciones"); // NOI18N
        jScrollPane1.setViewportView(jXTableBonificaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable jXTableBonificaciones;
    // End of variables declaration//GEN-END:variables
}
