/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelObservacion.java
 *
 * Created on 29-jun-2009, 11:25:13
 */

package ar.com.init.agros.view.components.panels;

/**
 *
 * @author fbobbio
 */
public class PanelObservacion extends javax.swing.JPanel{

    private static final long serialVersionUID = -1L;

    /** Creates new form PanelObservacion */
    public PanelObservacion() {
        initComponents();
    }

    public void clear()
    {
        jTextAreaObservacion.setText("");
    }

    public void disableFields()
    {
        jTextAreaObservacion.setEnabled(false);
    }

    public String getObservacion()
    {
        return jTextAreaObservacion.getText();
    }

    public void setObservacion(String observacion)
    {
        jTextAreaObservacion.setText(observacion);
    }

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        jTextAreaObservacion.setEditable(enabled);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObservacion = new javax.swing.JTextArea();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(PanelObservacion.class);
        setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("Form.border.title"))); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextAreaObservacion.setColumns(20);
        jTextAreaObservacion.setRows(5);
        jTextAreaObservacion.setName("jTextAreaObservacion"); // NOI18N
        jScrollPane1.setViewportView(jTextAreaObservacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaObservacion;
    // End of variables declaration//GEN-END:variables

}
