/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelSeleccionLote.java
 *
 * Created on 27-ago-2009, 19:55:36
 */
package ar.com.init.agros.view.components.panels;

import ar.com.init.agros.model.terreno.Campo;
import ar.com.init.agros.model.terreno.Lote;
import ar.com.init.agros.util.gui.validation.components.DoubleTableCellEditor;
import ar.com.init.agros.util.gui.validation.components.FrameNotifier;
import ar.com.init.agros.view.components.model.SeleccionLotesTableModel;
import java.util.List;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 * Panel de selección únicamente de lotes
 *
 * @author fbobbio
 */
public class PanelSeleccionLote extends javax.swing.JPanel
{

    private SeleccionLotesTableModel seleccionLotesTableModel;
    private FrameNotifier frameNotifier1;
    private Campo campo;

    /** Creates new form PanelSeleccionLote */
    public PanelSeleccionLote()
    {
        initComponents();
        seleccionLotesTableModel = new SeleccionLotesTableModel();
        jXTableLotes.setModel(seleccionLotesTableModel);
        jXTableLotes.setDefaultEditor(Double.class, new DoubleTableCellEditor(frameNotifier1));

        jXTableLotes.getModel().addTableModelListener(new TableModelListener()
        {

            @Override
            public void tableChanged(TableModelEvent e)
            {
                jCheckBoxSeleccionarCampo.setEnabled(seleccionLotesTableModel.getData() != null && seleccionLotesTableModel.getData().size() > 0);
                if (jXTableLotes.getRowCount() > 0 && jXTableLotes.getSelectedColumn() == SeleccionLotesTableModel.SELECCION_COLUMN_IDX)
                {
                    if (seleccionLotesTableModel.isAllSelected())
                    {
                        jCheckBoxSeleccionarCampo.setSelected(true);
                    }
                    else
                    {
                        jCheckBoxSeleccionarCampo.setSelected(false);
                    }
                }
            }
        });
        jXTableLotes.packAll();
    }

    public FrameNotifier getFrameNotifier1()
    {
        return frameNotifier1;
    }

    public void setFrameNotifier1(FrameNotifier frameNotifier1)
    {
        this.frameNotifier1 = frameNotifier1;
    }

    public List<Lote> getCheckedLotes()
    {
        return seleccionLotesTableModel.getCheckedData();
    }

    public void setData(List<Lote> data)
    {
        seleccionLotesTableModel.setData(data);
    }

    public void checkData(List<Lote> data)
    {
        seleccionLotesTableModel.checkData(data);
    }

    public void disableFieldsAndButtons()
    {
        jXTableLotes.setEditable(false);
        jCheckBoxSeleccionarCampo.setEnabled(false);
    }

    public void enableCheckBox(boolean val)
    {
        jCheckBoxSeleccionarCampo.setEnabled(val);
    }

    public void clear()
    {
        seleccionLotesTableModel.clear();
        campo = null;
        jCheckBoxSeleccionarCampo.setSelected(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTableLotes = new org.jdesktop.swingx.JXTable();
        jCheckBoxSeleccionarCampo = new javax.swing.JCheckBox();

        jXTableLotes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jXTableLotes);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(PanelSeleccionLote.class);
        jCheckBoxSeleccionarCampo.setText(resourceMap.getString("jCheckBoxSeleccionarCampo.text")); // NOI18N
        jCheckBoxSeleccionarCampo.setEnabled(false);
        jCheckBoxSeleccionarCampo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jCheckBoxSeleccionarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSeleccionarCampoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jCheckBoxSeleccionarCampo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxSeleccionarCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxSeleccionarCampoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBoxSeleccionarCampoActionPerformed
    {//GEN-HEADEREND:event_jCheckBoxSeleccionarCampoActionPerformed
        if (jCheckBoxSeleccionarCampo.isSelected())
        {
            seleccionLotesTableModel.changeAll(true);
        }
        else
        {
            seleccionLotesTableModel.changeAll(false);
        }
}//GEN-LAST:event_jCheckBoxSeleccionarCampoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxSeleccionarCampo;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable jXTableLotes;
    // End of variables declaration//GEN-END:variables

    public void setCampo(Campo campo)
    {
        this.campo = campo;
        setData(campo.getLotes());
    }

    public Campo getCampo()
    {
        return campo;
    }
}
