/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelCostoTotalCampania.java
 *
 * Created on 16-jun-2009, 11:47:22
 */
package ar.com.init.agros.view.components.panels;

import ar.com.init.agros.controller.PlanificacionAgroquimicoJpaController;
import ar.com.init.agros.model.Campania;
import ar.com.init.agros.model.ValorMoneda;
import ar.com.init.agros.util.gui.GUIUtility;
import ar.com.init.agros.util.gui.validation.components.FrameNotifier;
import ar.com.init.agros.view.components.model.CostoTotalCampaniaTableModel;

/**
 *
 * @author fbobbio
 */
public class PanelCostoTotalCampania extends javax.swing.JPanel
{
    private FrameNotifier frameNotifier;
    private CostoTotalCampaniaTableModel costoTotalTableModel;
    private PlanificacionAgroquimicoJpaController planificacionJpaController;

    /** Creates new form PanelCostoTotalCampania */
    public PanelCostoTotalCampania()
    {
        planificacionJpaController = new PlanificacionAgroquimicoJpaController();
        costoTotalTableModel = new CostoTotalCampaniaTableModel();
        initComponents();
        table.setModel(costoTotalTableModel);
        panelValorMoneda1.setEnabled(false);
        table.packAll();
    }

    /** Método que actualiza la tabla de costos por campaña, recibiendo la campaña
     *
     * @param campania
     */
    public void refreshTable(Campania campania)
    {
        costoTotalTableModel.setPlanificaciones(planificacionJpaController.findPlanificacionesByCampania(campania));
        panelValorMoneda1.setValorMoneda(new ValorMoneda(costoTotalTableModel.calcularCostoTotalCampania()));
    }

    public void clear()
    {
        GUIUtility.clearTable(table);
    }

    public void setFrameNotifier(FrameNotifier frameNotifier1)
    {
        this.frameNotifier = frameNotifier1;
    }

    public void disableFields()
    {
        panelValorMoneda1.setEnabled(false);
        table.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new org.jdesktop.swingx.JXTable();
        jLabel1 = new javax.swing.JLabel();
        panelValorMoneda1 = new ar.com.init.agros.view.components.valores.PanelValorMoneda();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.init.agros.view.Application.class).getContext().getResourceMap(PanelCostoTotalCampania.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N

        panelValorMoneda1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelValorMoneda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelValorMoneda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private ar.com.init.agros.view.components.valores.PanelValorMoneda panelValorMoneda1;
    private org.jdesktop.swingx.JXTable table;
    // End of variables declaration//GEN-END:variables
}
